use colecao_mangas;

insert into leituras (nome, quantidade_mangas)
values 
('A Voz do Silêncio', 4),
('Ataque dos Titãs', 42),
('Berserk', 44),
('Black Clover', 35),
('Bloom into You', 8),
('Burn the Witch', 1),
('Chainsaw Man', 16),
('Coin Laundry Lady', 1),
('Defense Devil', 10),
('Demon Slayer', 28),
('Divina Comédia', 2),
('Elfen Lied', 12),
('Faculdade de Mangá', 1),
('Frieren', 11),
('Gannibal: Vila de Canibais', 1),
('Gash Bell!!', 4),
('Gurren Lagann', 10),
('HoriMiya', 17),
('Hunter X Hunter', 37),
('I Sold my Life', 3),
('Jujutsu Kaisen', 27),
('Junji Ito: Obras', 19),
('Kaguya-Sama', 28),
('Made in Abyss', 9),
('Madoka Magica', 3),
('Makoto Shinkai: Obras', 6),
('Mangás BR', 6),
('Minha Adorável Cosplayer', 11),
('Monogatari Series', 22),
('My Hero Academia', 38),
('Naruto', 86),
('O Horizonte',	1),
('One Piece', 113),
('Quero Comer seu Pâncreas', 2),
('Re:Zero',	25),
('Sankarea', 11),
('Solo Leveling', 5),
('Spy X Family', 9),
('Tarareba', 1),
('Variante', 4),
('Yu Yu Hakusho', 19);

create table lista_de_mangas (
id int(15) auto_increment,
titulo varchar(80),
autor varchar(80),
volume varchar(15),
editora varchar(45),
edicao varchar(45),
colecao varchar(50),
primary key (id)
)
CHARACTER SET = latin1;

insert into lista_de_mangas(titulo, autor, volume, editora, edicao, colecao) 
values  

('Hunter X Hunter', 'Yoshihiro Togashi', '1', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '2', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '3', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '4', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '5', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '6', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '7', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '8', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '9', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '10', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '11', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '12', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '13', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '14', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '15', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '16', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '17', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '18', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '19', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '20', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '21', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '22', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '23', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '24', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '25', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '26', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '27', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '28', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '29', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '30', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '31', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '32', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '33', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '34', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '35', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '36', 'JBC', 'Padrão', 'Hunter X Hunter'),
('Hunter X Hunter', 'Yoshihiro Togashi', '37', 'JBC', 'Padrão', 'Hunter X Hunter'),

('Yu Yu Hakusho', 'Yoshihiro Togashi', '1', 'JBC', 'Padrão', 'Yu Yu Hakusho'), 
('Yu Yu Hakusho', 'Yoshihiro Togashi', '2', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '3', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '4', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '5', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '6', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '7', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '8', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '9', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '10', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '11', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '12', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '13', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '14', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '15', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '16', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '17', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '18', 'JBC', 'Padrão', 'Yu Yu Hakusho'),
('Yu Yu Hakusho', 'Yoshihiro Togashi', '19', 'JBC', 'Padrão', 'Yu Yu Hakusho'),

-- --

('Demon Slayer', 'Koyoharu Gotouge', '1', 'Panini', 'Padrão', 'Demon Slayer'), 
('Demon Slayer', 'Koyoharu Gotouge', 2, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 3, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 4, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 5, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 6, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 7, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 8, 'Panini', 'Padrão', 'Demon Slayer'), 
('Demon Slayer', 'Koyoharu Gotouge', 9, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 10, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 11, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 12, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 13, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 14, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 15, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 16, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 17, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 18, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 19, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 20, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 21, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 22, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer', 'Koyoharu Gotouge', 23, 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer Gaiden', 'Ryouji Hirane', 'Único', 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer Fanbook Oficial', 'Koyoharu Gotouge', 'I', 'Panini', 'Padrão', 'Demon Slayer'),
('Demon Slayer Fanbook Oficial', 'Koyoharu Gotouge', 'II', 'Panini', 'Padrão', 'Demon Slayer'),
('Kimetsu no Yaiba', 'Koyoharu Gotouge', '21', 'Shueisha', 'Japonesa Especial', 'Demon Slayer'),
('Kimetsu no Yaiba: Koyoharu Gotouge Gashū', 'Koyoharu Gotouge', 'Artbook', 'Shueisha', 'Japonesa', 'Demon Slayer'),


-- --

('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 1, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 2, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 3, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 4, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 5, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 6, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 7, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 8, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 9, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 10, 'Panini', 'Padrão', 'Frieren'),
('Frieren e a Jornada para o Além', 'Kanehito Yamada & Tsukasa Abe', 11, 'Panini', 'Padrão', 'Frieren'),

-- --

('Chainsaw Man', 'Tatsuki Fujimoto', 1, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 2, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 3, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 4, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 5, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 6, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 7, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 8, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 9, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 10, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 11, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 12, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 13, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 14, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 15, 'Panini', 'Padrão', 'Chainsaw Man'),
('Chainsaw Man', 'Tatsuki Fujimoto', 16, 'Panini', 'Padrão', 'Chainsaw Man'),

-- --

('Elfen Lied', 'Lynn Okamoto', 1, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 2, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 3, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 4, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 5, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 6, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 7, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 8, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 9, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 10, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 11, 'Panini', 'Padrão', 'Elfen Lied'),
('Elfen Lied', 'Lynn Okamoto', 12, 'Panini', 'Padrão', 'Elfen Lied'),

-- --

('Naruto', 'Masashi Kishimoto', 1, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 2, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 3, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 4, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 5, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 6, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 7, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 8, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 9, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 10, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 11, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 12, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 13, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 14, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 15, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 16, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 17, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 18, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 19, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 20, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 21, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 22, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 23, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 24, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 25, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 26, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 27, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 28, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 29, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 30, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 31, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 32, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 33, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 34, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 35, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 36, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 37, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 38, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 39, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 40, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 41, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 42, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 43, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 44, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 45, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 46, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 47, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 48, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 49, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 50, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 51, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 52, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 53, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 54, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 55, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 56, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 57, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 58, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 59, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 60, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 61, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 62, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 63, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 64, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 65, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 66, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 67, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 68, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 69, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 70, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 71, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 72, 'Panini', 'Padrão', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 70, 'Panini', 'Pocket', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 71, 'Panini', 'Pocket', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 72, 'Panini', 'Pocket', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 1, 'Panini', 'Gold', 'Naruto'),
('Naruto', 'Masashi Kishimoto', 72, 'Panini', 'Gold', 'Naruto'),
('Naruto Gaiden', 'Masashi Kishimoto', 'Único', 'Panini', 'Gold', 'Naruto'),
('Naruto The Last', 'Masashi Kishimoto & Maruo Kyozuka', 'Único', 'Panini', 'Novel', 'Naruto'),
('Naruto: Contemplações de Amor na Brisa de Primavera', 'Masashi Kishimoto & Tomohito Osaki', 'Único', 'Panini', 'Novel', 'Naruto'),
('Naruto: Um dia Perfeito para se Casar', 'Masashi Kishimoto & Shou Hinata', 'Único', 'Panini', 'Novel', 'Naruto'),
('Naruto: O Desabrochar das Flores Malignas', 'Masashi Kishimoto & Shin Towada', 'Único', 'Panini', 'Novel', 'Naruto'),
('Naruto: O Livro Secreto do Guerreiro', 'Masashi Kishimoto', 'Único', 'Panini', 'Guia', 'Naruto'),
('Naruto: O Livro Secreto do Confronto', 'Masashi Kishimoto', 'Único', 'Panini', 'Guia', 'Naruto'),
('Naruto: O Livro Secreto da Batalha', 'Masashi Kishimoto', 'Único', 'Panini', 'Guia', 'Naruto'),
('Naruto: O Livro Secreto da Formação', 'Masashi Kishimoto', 'Único', 'Panini', 'Guia', 'Naruto'),

-- --

('Ataque dos Titãs', 'Hajime Isayama', 1, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 2, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 3, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 4, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 5, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 6, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 7, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 8, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 9, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 10, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 11, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 12, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 13, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 14, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 15, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 16, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 17, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 18, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 19, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 20, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 21, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 22, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 23, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 24, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 25, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 26, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 27, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 28, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 29, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 30, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 31, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 32, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 33, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 34, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 34, 'Panini', 'Variante', 'Ataque dos Titãs'),
('Ataque dos Titãs', 'Hajime Isayama', 1, 'Panini', 'Reimpressão', 'Ataque dos Titãs'),
('Shingeki no Kyojin', 'Hajime Isayama', 1, 'Kodansha', 'Japonesa', 'Ataque dos Titãs'),
('Ataque dos Titãs: Outside', 'Hajime Isayama', 'Único', 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs: Inside', 'Hajime Isayama', 'Único', 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs: Answers', 'Hajime Isayama', 'Único', 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs: Lost Girls', 'Hajime Isayama', 1, 'Panini', 'Padrão', 'Ataque dos Titãs'),
('Ataque dos Titãs: Lost Girls', 'Hajime Isayama', 2, 'Panini', 'Padrão', 'Ataque dos Titãs'),


-- --

('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 0, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 1, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 2, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 3, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 3, 'Panini', 'Variante', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 4, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 5, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 6, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 7, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 8, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 8, 'Panini', 'Variante', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 9, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 10, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 11, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 12, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 13, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 14, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 15, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 16, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 17, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 18, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 19, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 20, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 21, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 22, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 23, 'Panini', 'Padrão', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Batalha de Feiticeiros', 'Gege Akutami', 24, 'Panini', 'Padrão', 'Jujutsu Kaisen'),

('Jujutsu Kaisen', 'Gege Akutami', 1, 'Shueisha', 'Japonesa', 'Jujutsu Kaisen'),
('Jujutsu Kaisen: Guia Oficial', 'Gege Akutami', 'Único', 'Panini', 'Padrão', 'Jujutsu Kaisen'),

-- --

('One Piece', 'Eiichiro Oda', 1, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 2, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 3, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 4, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 5, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 6, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 7, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 8, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 9, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 10, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 11, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 12, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 13, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 14, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 15, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 16, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 17, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 18, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 19, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 20, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 21, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 22, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 23, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 24, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 25, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 26, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 27, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 28, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 29, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 30, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 31, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 32, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 33, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 34, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 35, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 36, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 37, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 38, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 39, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 40, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 41, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 42, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 43, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 44, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 45, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 46, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 47, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 48, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 49, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 50, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 51, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 52, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 53, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 54, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 55, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 56, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 57, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 58, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 59, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 60, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 61, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 62, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 63, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 64, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 65, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 66, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 67, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 68, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 69, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 70, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 71, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 72, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 73, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 74, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 75, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 76, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 77, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 78, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 79, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 80, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 81, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 82, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 83, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 84, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 85, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 86, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 87, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 88, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 89, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 90, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 91, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 92, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 93, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 94, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 95, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 96, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 97, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 98, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 99, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 100, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 101, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 102, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 103, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 104, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 105, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 106, 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 107, 'Panini', 'Padrão', 'One Piece'),
('Wanted!', 'Eiichiro Oda', 'Único', 'Panini', 'Padrão', 'One Piece'),
('One Piece', 'Eiichiro Oda', 'Red', 'Panini', 'Databook', 'One Piece'),
('One Piece', 'Eiichiro Oda', 'Blue', 'Panini', 'Databook', 'One Piece'),
('One Piece', 'Eiichiro Oda', 'Yellow', 'Panini', 'Databook', 'One Piece'),
('One Piece', 'Eiichiro Oda', 'Green', 'Panini', 'Databook', 'One Piece'),
('One Piece', 'Eiichiro Oda', 'Blue Deep', 'Panini', 'Databook', 'One Piece'),

-- --

('Berserk','Kentaro Miura','1','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','2','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','3','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','4','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','5','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','6','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','7','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','8','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','9','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','10','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','11','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','12','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','13','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','14','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','15','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','16','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','17','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','18','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','19','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','20','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','21','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','22','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','23','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','24','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','25','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','26','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','27','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','28','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','29','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','30','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','31','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','32','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','33','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','34','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','35','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','36','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','37','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','38','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','39','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','40','Panini','Luxo', 'Berserk'),
('Berserk','Kentaro Miura','41','Panini','Variante', 'Berserk'),
('Berserk Guia Oficial','Kentaro Miura','Único','Panini','Luxo', 'Berserk'),
('Gigantomaquia','Kentaro Miura','Único','Panini','Luxo', 'Berserk'),
('Duranki','Kentaro Miura','Único','Panini','Luxo', 'Berserk'),

-- --

('Tomie', 'Junji Ito', '1', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('Tomie', 'Junji Ito', '2', '', 'Padrão', 'Junji Ito: Obras'),
('Frankenstein', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('A Sala de Aula que Derreteu', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('As Egocêntricas Maldições de Souichi', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('A Morada do Desertor', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('O Beco', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('O Encanamento que Geme', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('Mortos de Amor', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('Zona Fantasma', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('Sensor', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('Dismorfos', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('Calafrios', 'Junji Ito', 'Único', 'Pipoca & Nanquim', 'Padrão', 'Junji Ito: Obras'),
('Uzumaki', 'Junji Ito', 'Único', 'Devir', 'Padrão', 'Junji Ito: Obras'),
('Gyo', 'Junji Ito', 'Único', 'Devir', 'Padrão', 'Junji Ito: Obras'),
('Black Paradox', 'Junji Ito', 'Único', 'JBC', 'Padrão', 'Junji Ito: Obras'),
('Fragmentos do Horror', 'Junji Ito', 'Único', 'Darkside', 'Padrão', 'Junji Ito: Obras'),
('Contos de Horror da Mimi', 'Junji Ito', 'Único', 'Darkside', 'Padrão', 'Junji Ito: Obras'),
('Visões Grotescas','Junji Ito','Único','Pipoca & Nanquim','Artbook','Junji Ito: Obras'),

-- --

('My Hero Academia','Kohei Horikoshi','1','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','2','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','3','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','4','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','5','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','6','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','7','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','8','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','9','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','10','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','11','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','12','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','13','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','14','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','15','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','16','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','17','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','18','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','19','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','20','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','21','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','22','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','23','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','24','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','25','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','26','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','27','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','28','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','29','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','30','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','31','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','32','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','33','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','34','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','35','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','36','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','37','JBC','Padrão','My Hero Academia'),
('My Hero Academia','Kohei Horikoshi','38','JBC','Padrão','My Hero Academia'),

-- --

('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','1','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','2','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','3','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','4','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','5','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','6','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','7','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','8','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','9','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','10','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','11','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','12','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','13','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','14','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','15','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','16','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','17','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','18','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','19','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','20','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','21','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','22','NewPop','Novel','Re:Zero'),
('Re:Zero Começando uma Vida em Outro Mundo','Tappei Nagatsuki','23','NewPop','Novel','Re:Zero'),

('Re:Zero Contando as Crônicas do Outro Mundo','Tappei Nagatsuki','1','NewPop','Novel','Re:Zero'),
('Re:Zero Contando as Crônicas do Outro Mundo','Tappei Nagatsuki','2','NewPop','Novel','Re:Zero'),

-- --

('Black Clover','Yûki Tabata','1','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','2','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','3','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','4','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','5','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','6','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','7','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','8','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','9','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','10','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','11','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','12','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','13','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','14','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','15','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','16','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','17','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','18','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','19','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','20','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','21','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','22','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','23','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','24','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','25','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','26','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','27','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','28','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','29','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','30','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','31','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','32','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','33','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','34','Panini','Padrão', 'Black Clover'),
('Black Clover','Yûki Tabata','35','Panini','Padrão', 'Black Clover'),

-- --

('Kaguya-Sama: Love is War','Aka Akasaka','1','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','2','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','3','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','4','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','5','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','6','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','7','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','8','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','9','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','10','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','11','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','12','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','13','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','14','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','15','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','16','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','17','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','18','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','19','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','20','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','21','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','22','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','23','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','24','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','25','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','26','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','27','Panini','Padrão','Kaguya-Sama'),
('Kaguya-Sama: Love is War','Aka Akasaka','28','Panini','Padrão','Kaguya-Sama'),

-- --

('Minha Adorável Cosplayer','Shinichi Fukuda','1','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','2','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','3','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','4','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','5','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','6','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','7','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','8','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','9','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','10','Panini','Padrão','Minha Adorável Cosplayer'),
('Minha Adorável Cosplayer','Shinichi Fukuda','11','Panini','Padrão','Minha Adorável Cosplayer'),

-- --

('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','1','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','2','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','3','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','4','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','5','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','6','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','7','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','8','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','9','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','10','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','11','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','12','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','13','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','14','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','15','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun','Hero x Daisuke Hagiwara','16','Panini','Padrão','HoriMiya'),
('HoriMiya: Hori-san e Miyamura-kun Fragmentos de lembranças','Hero x Daisuke Hagiwara','17','Panini','Variante','HoriMiya'),

-- --

('Quero Comer seu Pâncreas','Idumo Kirihara','1','NewPop','Padrão', 'Quero Comer seu Pâncreas'),
('Quero Comer seu Pâncreas','Idumo Kirihara','2','NewPop','Padrão', 'Quero Comer seu Pâncreas'),
('5 Centímetros por Segundo','Makoto Shinkai e Yukiko Seike','Único','NewPop','Volume Único', 'Makoto Shinkai: Obras'),
('O Jardim das Palavras','Makoto Shinkai e Midori Motobashi','Único', 'NewPop', 'Padrão', 'Makoto Shinkai: Obras'),
('Ela e o Seu Gato','Makoto Shinkai e Tsubasa Yamaguchi','Único', 'NewPop','Padrão', 'Makoto Shinkai: Obras'),

-- --

('Puella Magi Madoka Magica', 'Magica Quartet', '1', 'NewPop', 'Padrão', 'Madoka Magica'),
('Puella Magi Madoka Magica', 'Magica Quartet', '2', 'NewPop', 'Padrão', 'Madoka Magica'),
('Puella Magi Madoka Magica', 'Magica Quartet', '3', 'NewPop', 'Padrão', 'Madoka Magica'),

-- --

('Tarareba', 'Kyo Hatsuki ', 'Único', 'Nova Sampa', 'Padrão', 'Tarareba'),
('Variante: Requiem for the World', 'Iqura Sugimoto', '1', 'Nova Sampa', 'Padrão', 'Variante'),
('Variante: Requiem for the World', 'Iqura Sugimoto', '2', 'Nova Sampa', 'Padrão', 'Variante'),
('Variante: Requiem for the World', 'Iqura Sugimoto', '3', 'Nova Sampa', 'Padrão', 'Variante'),
('Variante: Requiem for the World', 'Iqura Sugimoto', '4', 'Nova Sampa', 'Padrão', 'Variante'),

('Gurren Lagann', 'Kotaro Mori', '1', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '2', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '3', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '4', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '5', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '6', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '7', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '8', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '9', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),
('Gurren Lagann', 'Kotaro Mori', '10', 'Nova Sampa', 'Padrão', 'Gurren Lagann'),

-- --

('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '1', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '2', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '3', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '4', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '5', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '6', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '7', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '8', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '9', 'Panini', 'Padrão', 'Defense Devil'),
('Defense Devil', 'Youn In-Wan e Yang Kyung-Il', '10', 'Panini', 'Padrão', 'Defense Devil'),

-- --

('Gash Bell!!', 'Makoto Raiku', '1', 'MPEG', 'Kanzenban', 'Gash Bell!!'),
('Gash Bell!!', 'Makoto Raiku', '2', 'MPEG', 'Kanzenban', 'Gash Bell!!'),
('Gash Bell!!', 'Makoto Raiku', '3', 'MPEG', 'Kanzenban', 'Gash Bell!!'),
('Gash Bell!!', 'Makoto Raiku', '4', 'MPEG', 'Kanzenban', 'Gash Bell!!'),

('Gannibal: Vila de Canibais', 'Masaaki Ninomiya', '1', 'MPEG', 'Padrão', 'Gannibal: Vila de Canibais'),

-- --

('Sankarea', 'Mitsuru Hattori', '1', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '2', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '3', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '4', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '5', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '6', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '7', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '8', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '9', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '10', 'Panini', 'Padrão', 'Sankarea'),
('Sankarea', 'Mitsuru Hattori', '11', 'Panini', 'Padrão', 'Sankarea'),

('Burn The Witch', 'Tite Kubo', 'I', 'Panini', 'Padrão', 'Burn the Witch'),

-- --

('Coin Laundry Lady', 'Hiro Kiyohara', 'Único', 'JBC', 'Padrão', 'Coin Laundry Lady'),
('I Sold My Life For Ten Thousand Yen Per Year', 'Sugaru Miaki e Shouichi Tagushi', '1', 'JBC', 'Padrão','I Sold my Life'),
('I Sold My Life For Ten Thousand Yen Per Year', 'Sugaru Miaki e Shouichi Tagushi', '2', 'JBC', 'Padrão','I Sold my Life'),
('I Sold My Life For Ten Thousand Yen Per Year', 'Sugaru Miaki e Shouichi Tagushi', '3', 'JBC', 'Padrão','I Sold my Life'),
('O Tempo com Você', 'Makoto Shinkai e Wataru Kubota', '1', 'JBC', 'Padrão', 'Makoto Shinkai: Obras'),
('O Tempo com Você', 'Makoto Shinkai e Wataru Kubota', '2', 'JBC', 'Padrão', 'Makoto Shinkai: Obras'),
('O Tempo com Você', 'Makoto Shinkai e Wataru Kubota', '3', 'JBC', 'Padrão', 'Makoto Shinkai: Obras'),

-- --

('Bakemonogatari', 'NISIOISIN e Oh!great', '1', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '2', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '3', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '4', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '5', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '6', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '7', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '8', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '9', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '10', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '11', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '12', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '13', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '14', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '15', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '16', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '17', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '18', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '19', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '20', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '21', 'Panini', 'Padrão', 'Monogatari Series'),
('Bakemonogatari', 'NISIOISIN e Oh!great', '22', 'Panini', 'Padrão', 'Monogatari Series'),
-- --
('Solo Leveling', 'Chugong', '1', 'NewPop', 'Padrão', 'Solo Leveling'),
('Solo Leveling', 'Chugong', '2', 'NewPop', 'Padrão', 'Solo Leveling'),
('Solo Leveling', 'Chugong', '3', 'NewPop', 'Padrão', 'Solo Leveling'),
('Solo Leveling', 'Chugong', '4', 'NewPop', 'Padrão', 'Solo Leveling'),
('Solo Leveling', 'Chugong', '5', 'NewPop', 'Padrão', 'Solo Leveling'),
-- --
('Faculdade de Mangá', 'Osamu Tezuka', '', 'NewPop', 'Padrão', 'Faculdade de Mangá'),
('O Horizonte', 'Jung Ji Hun', '1', 'NewPop', 'Padrão', 'O Horizonte'),
('Divina Comédia', 'Go Nagai', '1', 'NewPop', 'Padrão', 'Divina Comédia'),
('Divina Comédia', 'Go Nagai', '2', 'NewPop', 'Padrão', 'Divina Comédia'),
('A Voz do Silêncio', 'Yoshitoki Oima', '1', 'NewPop', 'Definitiva', 'A Voz do Silêncio'),
('A Voz do Silêncio', 'Yoshitoki Oima', '2', 'NewPop', 'Definitiva', 'A Voz do Silêncio'),
('A Voz do Silêncio', 'Yoshitoki Oima', '3', 'NewPop', 'Definitiva', 'A Voz do Silêncio'),
('A Voz do Silêncio', 'Yoshitoki Oima', '4', 'NewPop', 'Definitiva', 'A Voz do Silêncio'),
-- --
('Bloom into You', 'Nio Nakatani', '1', 'Panini', 'Padrão', 'Bloom into You'),
('Bloom into You', 'Nio Nakatani', '2', 'Panini', 'Padrão', 'Bloom into You'),
('Bloom into You', 'Nio Nakatani', '3', 'Panini', 'Padrão', 'Bloom into You'),
('Bloom into You', 'Nio Nakatani', '4', 'Panini', 'Padrão', 'Bloom into You'),
('Bloom into You', 'Nio Nakatani', '5', 'Panini', 'Padrão', 'Bloom into You'),
('Bloom into You', 'Nio Nakatani', '6', 'Panini', 'Padrão', 'Bloom into You'),
('Bloom into You', 'Nio Nakatani', '7', 'Panini', 'Padrão', 'Bloom into You'),
('Bloom into You', 'Nio Nakatani', '8', 'Panini', 'Padrão', 'Bloom into You'),

('Spy X Family', 'Tatsuya Endo', '1', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '2', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '3', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '4', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '5', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '6', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '7', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '8', 'Panini', 'Padrão', 'Spy X Family'),
('Spy X Family', 'Tatsuya Endo', '9', 'Panini', 'Padrão', 'Spy X Family'),


-- --

('Made in Abyss', 'Akihito Tsukushi', '1', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '2', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '3', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '4', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '5', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '6', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '7', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '8', 'NewPop', 'Padrão', 'Made in Abyss'),
('Made in Abyss', 'Akihito Tsukushi', '9', 'NewPop', 'Padrão', 'Made in Abyss'),

-- --

('Hooligan', 'Jayson Santos', '1', 'Estudio Armon', 'Padrão', 'Mangás BR'),
('Hooligan', 'Jayson Santos', '2', 'Estudio Armon', 'Padrão', 'Mangás BR'),
('Hooligan', 'Jayson Santos', '3', 'Estudio Armon', 'Padrão', 'Mangás BR'),
('Utopian', 'Waldenis Lopes', '1', 'Estudio Armon', 'Padrão', 'Mangás BR'),
('HarmoniHQ', 'Estudio Armon Artistas', 'Único', 'Estudio Armon', 'Padrão', 'Mangás BR'),
('Spectrus: Paralisia do Sono', 'Thiago Spyked', 'Único', 'Crás Editora', 'Padrão', 'Mangás BR');
-- --